/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#ba162f",
        "tertiary-container": "#8690ae",
        "surface-variant": "#353534",
        "on-tertiary-container": "#1f2942",
        "on-primary-fixed": "#410008",
        "inverse: "on-surface": "#313030",
        error: "#ffb4ab",
        "surface-container": "#201f1f",
        "on-tertiary-fixed": "#101b33",
        "surface-container-low": "#1c1b1b",
        "on-secondary-container": "#b7b5b4",
        "on-surface": "#e5e2e1",
        "on-secondary": "#313030",
        "surface-bright": "#3a3939",
        "secondary-fixed-dim": "#c8c6c5",
        "on-secondary-fixed": "#1c1b1b",
        "on-primary-container": "#5b000f",
        "error-container": "#93000a",
        "on-error": "#690005",
        "surface-dim": "#131313",
        "outline-variant": "#5b403f",
        "primary-container": "#ff525d",
        outline: "#aa8988",
        "surface-container-lowest": "#0e0e0e",
        primary: "#ffb3b2",
        background: "#131313",
        secondary: "#c8c6c5",
        "tertiary-fixed": "#d9e2ff",
        "secondary-container": "#474746",
        "primary-fixed-dim": "#ffb3b2",
        tertiary: "#bcc6e6",
        "tertiary-fixed-dim": "#bcc6e6",
        "secondary-fixed": "#e5e2e1",
        "on-error-container": "#ffdad6",
        "surface-container-highest": "#353534",
        "primary-fixed": "#ffdad9",
        "inverse-surface": "#e5e2e1",
        "on-surface-variant": "#e3bebc",
        "on-primary": "#680013",
        "on-background": "#e5e2e1",
        "surface-container-high": "#2a2a2a",
        "on-secondary-fixed-variant": "#474746",
        "on-primary-fixed-variant": "#92001f",
        "surface-tint": "#ffb3b2",
        "on-tertiary-fixed-variant": "#3c4661",
        surface: "#131313",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        xs: "0.25rem",
        lg: "1.5rem",
        xl: "2rem",
        sm: "0.5rem",
        md: "1rem",
        margin: "2rem",
        gutter: "1.5rem",
      },
      fontFamily: {
        sans: ["Plus Jakarta Sans", "sans-serif"],
        headline: ["Plus Jakarta Sans", "sans-serif"],
        display: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Plus Jakarta Sans", "sans-serif"],
        label: ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["28px", { lineHeight: "1.3", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-md": ["36px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "label-sm": ["10px", { lineHeight: "1.2", fontWeight: "700" }],
        "label-lg": ["14px", { lineHeight: "1.2", letterSpacing: "0.01em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "1.2", fontWeight: "500" }],
        "headline-md": ["22px", { lineHeight: "1.4", fontWeight: "600" }],
      },
      boxShadow: {
        'watermelon-glow': '0 0 20px rgba(255, 82, 93, 0.3)',
        'watermelon-glow-hover': '0 0 30px rgba(255, 82, 93, 0.5)',
      },
    },
  },
  plugins: [],
}